/** Domain layer: pure grade rules. */
export const ABSENT_MARK='غ'; export const INCOMPLETE_MARK='__INCOMPLETE__'; export const EXAM_TERM_SITTINGS=2;
export function normalizeArabicLocal(str){return String(str==null?'':str).replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/\s+/g,' ').trim();}
export function isAbsentMark(v){return v===ABSENT_MARK;} export function isIncompleteMark(v){return v===INCOMPLETE_MARK;}
export function isExamComponent(name){return /امتحان|اختبار|تقييم\s*شهري/.test(normalizeArabicLocal(name||''));}
export function isExamLikeComponent(v){return v&&typeof v==='object'?(!!v.isMonthlyGrade||isExamComponent(v.name)):isExamComponent(v);}
export function isAttendanceComponent(name){return /نسبه|حضور|غياب/.test(normalizeArabicLocal(name));}
export function isAbsenceDaysComponent(name){const n=normalizeArabicLocal(name);return /غياب/.test(n)&&!/نسبه/.test(n);}
export function aggregateAbsentAwareValues(rawVals,mode){if(!rawVals||!rawVals.length)return null;const numeric=rawVals.filter(v=>!isAbsentMark(v));if(!numeric.length)return ABSENT_MARK;const sum=numeric.reduce((a,b)=>a+b,0);return mode==='sum'?sum:sum/numeric.length;}
export function lockKey(cls,subj,term,month){return String(cls)+'||'+String(subj)+'||'+String(term)+'||'+String(month);} export function monthLockKey(term,month){return String(term)+'||'+String(month);}
export function isTermLocked(db,term){return !!(db&&db.termLocks&&db.termLocks[term]);}
export function isGradeEntryLocked(db,cls,subjectName,term,month){if(!db)return false;if(db.globalLock)return true;if(isTermLocked(db,term))return true;if(db.monthLocks&&db.monthLocks[monthLockKey(term,month)])return true;if(db.locks&&db.locks[lockKey(cls,subjectName,term,month)])return true;return false;}
export function toWesternDigits(str){return String(str==null?'':str).replace(/[٠-٩]/g,d=>String(d.charCodeAt(0)-0x0660)).replace(/[۰-۹]/g,d=>String(d.charCodeAt(0)-0x06F0));}
export function isAbsentInputText(raw){return normalizeArabicLocal(String(raw==null?'':raw)).trim()==='غ';}
export function parseStrictGradeInput(raw,maxScore){const original=String(raw==null?'':raw).trim();if(!original)return{ok:true,score:null,reason:''};if(isAbsentInputText(original))return{ok:true,score:ABSENT_MARK,reason:''};const s=toWesternDigits(original).replace(/٫/g,'.').replace(/,/g,'.').replace(/\s+/g,'');if(/[a-zA-Z\u0600-\u06FF]/.test(s)&&!isAbsentInputText(s))return{ok:false,score:null,reason:'يُسمح فقط بالأرقام أو «غ»'};if(/[^0-9.]/.test(s))return{ok:false,score:null,reason:'رموز غير مسموحة'};if((s.match(/\./g)||[]).length>1)return{ok:false,score:null,reason:'أكثر من علامة عشرية واحدة (مثال: 9..5)'};if(!(/^\d+(\.\d+)?$/.test(s)||/^\.\d+$/.test(s)))return{ok:false,score:null,reason:'صيغة غير صحيحة'};const num=Number(s);if(!Number.isFinite(num)||num<0)return{ok:false,score:null,reason:'قيمة غير صالحة'};const max=(maxScore===undefined||maxScore===null||maxScore==='')?null:Number(maxScore);if(max!=null&&Number.isFinite(max)&&num>max)return{ok:false,score:null,reason:'تتجاوز الحد ('+max+')'};return{ok:true,score:num,reason:''};}
export const gradeRules={ABSENT_MARK,INCOMPLETE_MARK,EXAM_TERM_SITTINGS,isAbsentMark,isIncompleteMark,isExamComponent,isExamLikeComponent,isAttendanceComponent,isAbsenceDaysComponent,aggregateAbsentAwareValues,lockKey,monthLockKey,isTermLocked,isGradeEntryLocked,toWesternDigits,isAbsentInputText,parseStrictGradeInput,normalizeArabicLocal};
