-- STEP 53 — Supabase New Project Bootstrap
-- Grade System Pro 25.6.x
-- Run this script ONCE in the NEW Supabase project SQL Editor.
-- It is intentionally idempotent where practical.
-- IMPORTANT: This script does NOT create Auth users or passwords.

BEGIN;

-- ============================================================
-- 1. Core tables
-- ============================================================
CREATE TABLE IF NOT EXISTS public.grade_system_state (
  id text PRIMARY KEY,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'teacher'
    CHECK (role IN ('superadmin','stageadmin','monitor','teacher')),
  full_name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  stage_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  teacher_id text,
  sections jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profiles_stage_ids_array CHECK (jsonb_typeof(stage_ids) = 'array')
);

CREATE TABLE IF NOT EXISTS public.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  actor_name text NOT NULL DEFAULT '',
  actor_role text NOT NULL DEFAULT '',
  stage_id text,
  stage_name text,
  action text NOT NULL DEFAULT '',
  details text NOT NULL DEFAULT '',
  level text NOT NULL DEFAULT 'info',
  app_version text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created_at ON public.audit_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_stage_id ON public.audit_events (stage_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles (role);

ALTER TABLE public.grade_system_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 2. Security helper functions
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.is_active IS DISTINCT FROM false
      AND p.role = 'superadmin'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin_role()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.is_active IS DISTINCT FROM false
      AND p.role IN ('superadmin','stageadmin','monitor')
  );
$$;

CREATE OR REPLACE FUNCTION public.can_access_stage_row(row_id text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE
    WHEN public.is_superadmin() THEN true
    WHEN row_id IS NULL OR row_id NOT LIKE 'stage_%' THEN false
    ELSE EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_active IS DISTINCT FROM false
        AND jsonb_typeof(p.stage_ids) = 'array'
        AND p.stage_ids ? substr(row_id, 7)
    )
  END;
$$;

-- ============================================================
-- 3. profiles RLS
-- ============================================================
DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT TO authenticated
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- No client-side INSERT/DELETE policy: profile provisioning is administrative.
DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
DROP POLICY IF EXISTS "profiles_delete_own" ON public.profiles;

-- ============================================================
-- 4. grade_system_state RLS
-- ============================================================
DROP POLICY IF EXISTS "state_deny_anon" ON public.grade_system_state;
CREATE POLICY "state_deny_anon" ON public.grade_system_state
  FOR ALL TO anon USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "state_select_root_public" ON public.grade_system_state;
CREATE POLICY "state_select_root_public" ON public.grade_system_state
  FOR SELECT TO authenticated USING (id = 'root_public');

DROP POLICY IF EXISTS "state_select_root_secure" ON public.grade_system_state;
CREATE POLICY "state_select_root_secure" ON public.grade_system_state
  FOR SELECT TO authenticated USING (id = 'root_secure' AND public.is_superadmin());

DROP POLICY IF EXISTS "state_select_root_meta_legacy" ON public.grade_system_state;
CREATE POLICY "state_select_root_meta_legacy" ON public.grade_system_state
  FOR SELECT TO authenticated USING (id = 'root_meta' AND public.is_superadmin());

DROP POLICY IF EXISTS "state_select_stages" ON public.grade_system_state;
CREATE POLICY "state_select_stages" ON public.grade_system_state
  FOR SELECT TO authenticated USING (id LIKE 'stage_%' AND public.can_access_stage_row(id));

DROP POLICY IF EXISTS "state_select_other_admin" ON public.grade_system_state;
CREATE POLICY "state_select_other_admin" ON public.grade_system_state
  FOR SELECT TO authenticated USING (
    id NOT IN ('root_public','root_secure','root_meta')
    AND id NOT LIKE 'stage_%'
    AND public.is_admin_role()
  );

DROP POLICY IF EXISTS "state_insert_rows" ON public.grade_system_state;
CREATE POLICY "state_insert_rows" ON public.grade_system_state
  FOR INSERT TO authenticated
  WITH CHECK (
    (id = 'root_public' AND public.is_admin_role()) OR
    (id = 'root_secure' AND public.is_superadmin()) OR
    (id = 'root_meta' AND public.is_superadmin()) OR
    (id LIKE 'stage_%' AND public.can_access_stage_row(id)) OR
    (id NOT IN ('root_public','root_secure','root_meta') AND id NOT LIKE 'stage_%' AND public.is_admin_role())
  );

DROP POLICY IF EXISTS "state_update_rows" ON public.grade_system_state;
CREATE POLICY "state_update_rows" ON public.grade_system_state
  FOR UPDATE TO authenticated
  USING (
    (id = 'root_public' AND public.is_admin_role()) OR
    (id = 'root_secure' AND public.is_superadmin()) OR
    (id = 'root_meta' AND public.is_superadmin()) OR
    (id LIKE 'stage_%' AND public.can_access_stage_row(id)) OR
    (id NOT IN ('root_public','root_secure','root_meta') AND id NOT LIKE 'stage_%' AND public.is_admin_role())
  )
  WITH CHECK (
    (id = 'root_public' AND public.is_admin_role()) OR
    (id = 'root_secure' AND public.is_superadmin()) OR
    (id = 'root_meta' AND public.is_superadmin()) OR
    (id LIKE 'stage_%' AND public.can_access_stage_row(id)) OR
    (id NOT IN ('root_public','root_secure','root_meta') AND id NOT LIKE 'stage_%' AND public.is_admin_role())
  );

DROP POLICY IF EXISTS "state_delete_admin" ON public.grade_system_state;
CREATE POLICY "state_delete_admin" ON public.grade_system_state
  FOR DELETE TO authenticated
  USING (public.is_admin_role());

-- ============================================================
-- 5. audit_events RLS
-- ============================================================
DROP POLICY IF EXISTS "audit_events_insert_auth" ON public.audit_events;
CREATE POLICY "audit_events_insert_auth" ON public.audit_events
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "audit_events_select_admin" ON public.audit_events;
CREATE POLICY "audit_events_select_admin" ON public.audit_events
  FOR SELECT TO authenticated USING (public.is_admin_role());

-- No UPDATE/DELETE policies for normal client users.
DROP POLICY IF EXISTS "audit_events_update" ON public.audit_events;
DROP POLICY IF EXISTS "audit_events_delete" ON public.audit_events;

-- ============================================================
-- 6. Storage bucket
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('workbook-originals', 'workbook-originals', false)
ON CONFLICT (id) DO UPDATE SET public = false;

-- Storage path format used by the application:
-- <base64url(stageId)>/<base64url(gradeMetaKey)>.xlsx
CREATE OR REPLACE FUNCTION public.storage_path_stage_id(object_name text)
RETURNS text
LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  token text;
  padded text;
BEGIN
  token := split_part(COALESCE(object_name,''), '/', 1);
  IF token = '' THEN RETURN NULL; END IF;
  token := replace(replace(token, '-', '+'), '_', '/');
  padded := token || CASE mod(length(token), 4)
    WHEN 2 THEN '=='
    WHEN 3 THEN '='
    WHEN 0 THEN ''
    ELSE ''
  END;
  BEGIN
    RETURN convert_from(decode(padded, 'base64'), 'UTF8');
  EXCEPTION WHEN others THEN
    RETURN NULL;
  END;
END;
$$;

CREATE OR REPLACE FUNCTION public.can_access_storage_object(object_name text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.is_superadmin()
    OR EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.is_active IS DISTINCT FROM false
        AND jsonb_typeof(p.stage_ids) = 'array'
        AND p.stage_ids ? public.storage_path_stage_id(object_name)
    );
$$;

DROP POLICY IF EXISTS "workbooks_select_stage" ON storage.objects;
CREATE POLICY "workbooks_select_stage" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'workbook-originals' AND public.can_access_storage_object(name));

DROP POLICY IF EXISTS "workbooks_insert_stage" ON storage.objects;
CREATE POLICY "workbooks_insert_stage" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'workbook-originals' AND public.can_access_storage_object(name));

DROP POLICY IF EXISTS "workbooks_update_stage" ON storage.objects;
CREATE POLICY "workbooks_update_stage" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'workbook-originals' AND public.can_access_storage_object(name))
  WITH CHECK (bucket_id = 'workbook-originals' AND public.can_access_storage_object(name));

DROP POLICY IF EXISTS "workbooks_delete_stage" ON storage.objects;
CREATE POLICY "workbooks_delete_stage" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'workbook-originals' AND public.can_access_storage_object(name));

COMMIT;

-- ============================================================
-- POST-BOOTSTRAP NOTES
-- ============================================================
-- 1) Create the Superadmin in Authentication → Users.
-- 2) Insert its UUID into public.profiles with role='superadmin'.
-- 3) Create stageadmin/monitor/teacher Auth users and corresponding profiles.
-- 4) For stage-scoped users, stage_ids must be JSONB arrays, e.g. '["primary"]'.
-- 5) Do NOT put a database password/direct connection string in frontend files.
